#!/usr/local/env bash

set -eux

## install vim

sudo apt-get update
sudo apt-get install vim tmux -y

## install docker from //docs.docker.com/install/linux/docker-ce/ubuntu/ 
sudo apt-get install \
    apt-transport-https \
    ca-certificates \
    curl \
    gnupg-agent \
    software-properties-common

curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

sudo apt-key fingerprint 0EBFCD88

sudo add-apt-repository \
   "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
   $(lsb_release -cs) \
   stable"

sudo apt-get update
sudo apt-get install docker-ce docker-ce-cli containerd.io -y

## install nvidia driver
## For https://www.nvidia.com/download/driverResults.aspx/118955/en-us

sudo apt-key adv --fetch-keys http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64/7fa2af80.pub
sudo sh -c 'echo "deb http://developer.download.nvidia.com/compute/cuda/repos/ubuntu1604/x86_64 /" > /etc/apt/sources.list.d/cuda.list'
sudo apt-get update
sudo apt-get -y --no-install-recommends install cuda-drivers

## install nvidia-docker form https://github.com/NVIDIA/nvidia-docker

# Add the package repositories
curl -s -L https://nvidia.github.io/nvidia-docker/gpgkey | \
  sudo apt-key add -
distribution=$(. /etc/os-release;echo $ID$VERSION_ID)
curl -s -L https://nvidia.github.io/nvidia-docker/$distribution/nvidia-docker.list | \
  sudo tee /etc/apt/sources.list.d/nvidia-docker.list

sudo apt-get update

# Install nvidia-docker2 and reload the Docker daemon configuration
sudo apt-get install nvidia-docker2 -y
sudo pkill -SIGHUP dockerd

# Test nvidia-smi with the latest official CUDA image
#docker run --runtime=nvidia --rm nvidia/cuda:9.0-base nvidia-smi
